// ============================================================
// Fuente única de verdad del catálogo DFSAS Tienda.
// Basado en las categorías y productos reales de
// dutyfreeshopatlanticosur.com (relevados 2026-07).
// `node scripts/generate-catalog.mjs` regenera:
//   - supabase/seed.sql
//   - src/store/demoCatalog.ts
//   - public/img/products/*.svg y public/img/categories/*.svg
// ============================================================

export const categories = [
  {
    slug: 'bebidas',
    nameEs: 'Bebidas',
    namePt: 'Bebidas',
    nameEn: 'Spirits & Wines',
    sort: 1,
    icon: 'bottle',
    gradient: ['#7a4a08', '#2b1a02'],
  },
  {
    slug: 'perfumeria',
    nameEs: 'Perfumería',
    namePt: 'Perfumaria',
    nameEn: 'Fragrances & Beauty',
    sort: 2,
    icon: 'perfume',
    gradient: ['#8e3b6e', '#2c1130'],
  },
  {
    slug: 'electronica',
    nameEs: 'Electrónica',
    namePt: 'Eletrônicos',
    nameEn: 'Electronics',
    sort: 3,
    icon: 'headphones',
    gradient: ['#1d629c', '#0e1122'],
  },
  {
    slug: 'comestibles',
    nameEs: 'Comestibles',
    namePt: 'Comestíveis',
    nameEn: 'Food & Sweets',
    sort: 4,
    icon: 'chocolate',
    gradient: ['#8a3b1e', '#2e0f06'],
  },
  {
    slug: 'moda',
    nameEs: 'Moda y Accesorios',
    namePt: 'Moda e Acessórios',
    nameEn: 'Fashion & Accessories',
    sort: 5,
    icon: 'sunglasses',
    gradient: ['#20666a', '#081f21'],
  },
  {
    slug: 'juguetes',
    nameEs: 'Juguetes',
    namePt: 'Brinquedos',
    nameEn: 'Toys',
    sort: 6,
    icon: 'brick',
    gradient: ['#b06a10', '#3c2103'],
  },
  {
    slug: 'viaje',
    nameEs: 'Artículos de Viaje',
    namePt: 'Artigos de Viagem',
    nameEn: 'Travel',
    sort: 7,
    icon: 'suitcase',
    gradient: ['#2e6b46', '#0b2416'],
  },
  {
    slug: 'home',
    nameEs: 'Home & Design',
    namePt: 'Casa & Design',
    nameEn: 'Home & Design',
    sort: 8,
    icon: 'thermo',
    gradient: ['#4d5568', '#14161f'],
  },
];

// Cada producto: variants [{ sku, label, priceUsd, stock }]
export const products = [
  // ------------------------- BEBIDAS -------------------------
  {
    slug: 'jameson-caskmates-stout',
    category: 'bebidas',
    brand: 'Jameson',
    name: 'Caskmates Stout Edition',
    icon: 'bottle',
    featured: true,
    descEs: 'Whiskey irlandés terminado en barricas de cerveza stout: notas de cacao, café y un final suave.',
    descPt: 'Whiskey irlandês finalizado em barris de cerveja stout: notas de cacau, café e final suave.',
    descEn: 'Irish whiskey finished in stout beer casks: cocoa and coffee notes with a smooth finish.',
    variants: [{ sku: 'BEB-JAM-CM-750', label: '750 ml', priceUsd: 28.0, stock: 36 }],
  },
  {
    slug: 'johnnie-walker-black',
    category: 'bebidas',
    brand: 'Johnnie Walker',
    name: 'Black Label 12 Años',
    icon: 'bottle',
    featured: true,
    descEs: 'El blend escocés icónico, madurado 12 años. Formato 3 litros exclusivo de duty free.',
    descPt: 'O blend escocês icônico, maturado por 12 anos. Formato 3 litros exclusivo de duty free.',
    descEn: 'The iconic Scotch blend, aged 12 years. Travel-exclusive 3-litre format available.',
    variants: [
      { sku: 'BEB-JWB-1L', label: '1 L', priceUsd: 36.0, stock: 48 },
      { sku: 'BEB-JWB-3L', label: '3 L', priceUsd: 110.0, stock: 8 },
    ],
  },
  {
    slug: 'chivas-regal-12',
    category: 'bebidas',
    brand: 'Chivas Regal',
    name: 'Chivas Regal 12 Años',
    icon: 'bottle',
    featured: false,
    descEs: 'Scotch whisky de 12 años, redondo y cremoso, con notas de miel y manzana madura.',
    descPt: 'Scotch whisky de 12 anos, redondo e cremoso, com notas de mel e maçã madura.',
    descEn: 'A rich, smooth 12-year-old Scotch with honey and ripe apple notes.',
    variants: [
      { sku: 'BEB-CHV12-750', label: '750 ml', priceUsd: 30.0, stock: 30 },
      { sku: 'BEB-CHV12-1L', label: '1 L', priceUsd: 38.0, stock: 24 },
    ],
  },
  {
    slug: 'jack-daniels-old-no7',
    category: 'bebidas',
    brand: "Jack Daniel's",
    name: 'Old No. 7 Tennessee Whiskey',
    icon: 'bottle',
    featured: false,
    descEs: 'El clásico de Tennessee filtrado gota a gota en carbón de arce. Suave y con carácter.',
    descPt: 'O clássico do Tennessee filtrado gota a gota em carvão de bordo. Suave e com caráter.',
    descEn: 'The Tennessee classic, charcoal-mellowed drop by drop. Smooth with character.',
    variants: [{ sku: 'BEB-JD7-1L', label: '1 L', priceUsd: 33.0, stock: 40 }],
  },
  {
    slug: 'absolut-vodka',
    category: 'bebidas',
    brand: 'Absolut',
    name: 'Absolut Vodka',
    icon: 'bottle',
    featured: false,
    descEs: 'Vodka sueco de trigo de invierno, destilado de forma continua para una pureza excepcional.',
    descPt: 'Vodka sueca de trigo de inverno, destilada continuamente para uma pureza excepcional.',
    descEn: 'Swedish winter-wheat vodka, continuously distilled for exceptional purity.',
    variants: [{ sku: 'BEB-ABS-1L', label: '1 L', priceUsd: 15.0, stock: 60 }],
  },
  {
    slug: 'grey-goose',
    category: 'bebidas',
    brand: 'Grey Goose',
    name: 'Grey Goose Vodka',
    icon: 'bottle',
    featured: false,
    descEs: 'Vodka premium francés elaborado con trigo de Picardía y agua de manantial natural.',
    descPt: 'Vodka premium francesa feita com trigo da Picardia e água de nascente natural.',
    descEn: 'Premium French vodka crafted from Picardy wheat and natural spring water.',
    variants: [{ sku: 'BEB-GG-1L', label: '1 L', priceUsd: 42.0, stock: 18 }],
  },
  {
    slug: 'bombay-sapphire',
    category: 'bebidas',
    brand: 'Bombay Sapphire',
    name: 'London Dry Gin',
    icon: 'bottle',
    featured: false,
    descEs: 'Gin destilado al vapor con 10 botánicos seleccionados a mano. El alma del gin tonic perfecto.',
    descPt: 'Gin destilado a vapor com 10 botânicos selecionados à mão. A alma do gin tônica perfeito.',
    descEn: 'Vapour-infused gin with 10 hand-selected botanicals. The soul of a perfect G&T.',
    variants: [{ sku: 'BEB-BOM-1L', label: '1 L', priceUsd: 24.0, stock: 32 }],
  },
  {
    slug: 'baileys-original',
    category: 'bebidas',
    brand: 'Baileys',
    name: 'Original Irish Cream',
    icon: 'bottle',
    featured: false,
    descEs: 'La crema irlandesa original: whiskey, crema fresca y cacao en perfecta armonía.',
    descPt: 'O creme irlandês original: whiskey, creme fresco e cacau em perfeita harmonia.',
    descEn: 'The original Irish cream: whiskey, fresh dairy cream and cocoa in perfect harmony.',
    variants: [{ sku: 'BEB-BAI-1L', label: '1 L', priceUsd: 19.0, stock: 28 }],
  },
  {
    slug: 'lagarde-dolce-espumante',
    category: 'bebidas',
    brand: 'Lagarde',
    name: 'Dolce Espumante',
    icon: 'sparkling',
    featured: false,
    descEs: 'Espumante dulce natural de bodega mendocina, fresco y frutado. Ideal para brindar.',
    descPt: 'Espumante doce natural de vinícola mendocina, fresco e frutado. Ideal para brindar.',
    descEn: 'Naturally sweet sparkling wine from Mendoza — fresh, fruity, made for a toast.',
    variants: [{ sku: 'BEB-LAG-750', label: '750 ml', priceUsd: 14.0, stock: 26 }],
  },
  {
    slug: 'dpoeti-rosso-montalcino',
    category: 'bebidas',
    brand: 'D.Poeti',
    name: 'Rosso di Montalcino DOC',
    icon: 'wine',
    featured: false,
    descEs: 'Tinto toscano de uva Sangiovese, elegante y especiado, con denominación de origen.',
    descPt: 'Tinto toscano de uva Sangiovese, elegante e condimentado, com denominação de origem.',
    descEn: 'Tuscan Sangiovese red — elegant, spicy, with protected designation of origin.',
    variants: [{ sku: 'BEB-DPO-750', label: '750 ml', priceUsd: 26.0, stock: 15 }],
  },
  // ----------------------- PERFUMERÍA ------------------------
  {
    slug: 'prada-la-femme-intense',
    category: 'perfumeria',
    brand: 'Prada',
    name: 'La Femme Intense EDP',
    icon: 'perfume',
    featured: true,
    descEs: 'Frangipani, tuberosa y vainilla en una interpretación intensa y envolvente de la feminidad.',
    descPt: 'Frangipani, tuberosa e baunilha em uma interpretação intensa e envolvente da feminilidade.',
    descEn: 'Frangipani, tuberose and vanilla in an intense, enveloping take on femininity.',
    variants: [{ sku: 'PER-PLF-50', label: '50 ml', priceUsd: 96.0, stock: 14 }],
  },
  {
    slug: 'paco-rabanne-pure-xs-night',
    category: 'perfumeria',
    brand: 'Paco Rabanne',
    name: 'Pure XS Night EDP',
    icon: 'perfume',
    featured: false,
    descEs: 'Oriental ambarado con jengibre, cacao y vainilla bourbon. Seducción nocturna.',
    descPt: 'Oriental ambarado com gengibre, cacau e baunilha bourbon. Sedução noturna.',
    descEn: 'Amber oriental with ginger, cacao and bourbon vanilla. Night-time seduction.',
    variants: [
      { sku: 'PER-PXN-50', label: '50 ml', priceUsd: 78.0, stock: 16 },
      { sku: 'PER-PXN-100', label: '100 ml', priceUsd: 105.0, stock: 10 },
    ],
  },
  {
    slug: 'lancome-la-vie-est-belle-leclat',
    category: 'perfumeria',
    brand: 'Lancôme',
    name: "La Vie Est Belle L'Éclat EDT",
    icon: 'perfume',
    featured: false,
    descEs: 'La felicidad hecha fragancia: azahar luminoso, jazmín y un fondo cálido de vainilla.',
    descPt: 'A felicidade em fragrância: flor de laranjeira luminosa, jasmim e fundo quente de baunilha.',
    descEn: 'Happiness as a fragrance: luminous orange blossom, jasmine and a warm vanilla base.',
    variants: [{ sku: 'PER-LVB-50', label: '50 ml', priceUsd: 89.0, stock: 12 }],
  },
  {
    slug: 'prada-luna-rossa',
    category: 'perfumeria',
    brand: 'Prada',
    name: 'Luna Rossa EDT',
    icon: 'perfume',
    featured: false,
    descEs: 'Frescura deportiva de lavanda y menta inspirada en la vela de competición.',
    descPt: 'Frescor esportivo de lavanda e menta inspirado na vela de competição.',
    descEn: 'Sporty freshness of lavender and mint, inspired by competitive sailing.',
    variants: [
      { sku: 'PER-PLR-50', label: '50 ml', priceUsd: 72.0, stock: 15 },
      { sku: 'PER-PLR-100', label: '100 ml', priceUsd: 98.0, stock: 9 },
    ],
  },
  {
    slug: 'chanel-n5-edp',
    category: 'perfumeria',
    brand: 'Chanel',
    name: 'N°5 EDP',
    icon: 'perfume',
    featured: true,
    descEs: 'El perfume más famoso del mundo: aldehídos, rosa de mayo y jazmín de Grasse.',
    descPt: 'O perfume mais famoso do mundo: aldeídos, rosa de maio e jasmim de Grasse.',
    descEn: 'The world’s most famous perfume: aldehydes, May rose and Grasse jasmine.',
    variants: [
      { sku: 'PER-CH5-50', label: '50 ml', priceUsd: 128.0, stock: 10 },
      { sku: 'PER-CH5-100', label: '100 ml', priceUsd: 168.0, stock: 6 },
    ],
  },
  {
    slug: 'dior-sauvage-edt',
    category: 'perfumeria',
    brand: 'Dior',
    name: 'Sauvage EDT',
    icon: 'perfume',
    featured: false,
    descEs: 'Bergamota de Calabria y ambroxan sobre un fondo mineral. Frescura radicalmente masculina.',
    descPt: 'Bergamota da Calábria e ambroxan sobre um fundo mineral. Frescor radicalmente masculino.',
    descEn: 'Calabrian bergamot and ambroxan over a mineral base. Radically fresh and masculine.',
    variants: [
      { sku: 'PER-DSV-60', label: '60 ml', priceUsd: 95.0, stock: 14 },
      { sku: 'PER-DSV-100', label: '100 ml', priceUsd: 122.0, stock: 8 },
    ],
  },
  {
    slug: 'ch-212-vip-rose',
    category: 'perfumeria',
    brand: 'Carolina Herrera',
    name: '212 VIP Rosé EDP',
    icon: 'perfume',
    featured: false,
    descEs: 'Champagne rosé, flor de durazno y almizcle: el espíritu de la fiesta neoyorquina.',
    descPt: 'Champagne rosé, flor de pêssego e almíscar: o espírito da festa nova-iorquina.',
    descEn: 'Rosé champagne, peach blossom and musk: the spirit of the New York party.',
    variants: [{ sku: 'PER-212R-80', label: '80 ml', priceUsd: 92.0, stock: 12 }],
  },
  {
    slug: 'armani-acqua-di-gio',
    category: 'perfumeria',
    brand: 'Giorgio Armani',
    name: 'Acqua di Giò EDT',
    icon: 'perfume',
    featured: false,
    descEs: 'Un clásico marino mediterráneo: cítricos, jazmín acuático y maderas cálidas.',
    descPt: 'Um clássico marinho mediterrâneo: cítricos, jasmim aquático e madeiras quentes.',
    descEn: 'A Mediterranean marine classic: citrus, aquatic jasmine and warm woods.',
    variants: [
      { sku: 'PER-ADG-50', label: '50 ml', priceUsd: 74.0, stock: 16 },
      { sku: 'PER-ADG-100', label: '100 ml', priceUsd: 99.0, stock: 11 },
    ],
  },
  {
    slug: 'lancome-advanced-genifique',
    category: 'perfumeria',
    brand: 'Lancôme',
    name: 'Advanced Génifique Sérum',
    icon: 'cream',
    featured: false,
    descEs: 'Sérum de tratamiento con prebióticos que fortalece la barrera de la piel y aporta luminosidad.',
    descPt: 'Sérum de tratamento com prebióticos que fortalece a barreira da pele e traz luminosidade.',
    descEn: 'Prebiotic treatment serum that strengthens the skin barrier and restores radiance.',
    variants: [{ sku: 'PER-LAG-50', label: '50 ml', priceUsd: 105.0, stock: 9 }],
  },
  {
    slug: 'mac-retro-matte-ruby-woo',
    category: 'perfumeria',
    brand: 'M·A·C',
    name: 'Retro Matte Lipstick Ruby Woo',
    icon: 'lipstick',
    featured: false,
    descEs: 'El rojo mate universal de M·A·C, de acabado retro y larga duración.',
    descPt: 'O vermelho fosco universal da M·A·C, com acabamento retrô e longa duração.',
    descEn: 'M·A·C’s universally flattering matte red with a long-wearing retro finish.',
    variants: [{ sku: 'PER-MAC-RW', label: '3 g', priceUsd: 21.0, stock: 30 }],
  },
  // ----------------------- ELECTRÓNICA -----------------------
  {
    slug: 'xiaomi-redmi-buds',
    category: 'electronica',
    brand: 'Xiaomi',
    name: 'Redmi Buds True Wireless',
    icon: 'earbuds',
    featured: false,
    descEs: 'Auriculares true wireless con estuche de carga, Bluetooth 5.3 y cancelación de ruido en llamadas.',
    descPt: 'Fones true wireless com estojo de carga, Bluetooth 5.3 e cancelamento de ruído em chamadas.',
    descEn: 'True wireless earbuds with charging case, Bluetooth 5.3 and call noise cancellation.',
    variants: [{ sku: 'ELE-XRB-TWS', label: 'Único', priceUsd: 29.0, stock: 42 }],
  },
  {
    slug: 'logitech-k400-plus',
    category: 'electronica',
    brand: 'Logitech',
    name: 'Teclado Inalámbrico K400 Plus',
    icon: 'keyboard',
    featured: false,
    descEs: 'Teclado inalámbrico con touchpad integrado, ideal para smart TV y home office.',
    descPt: 'Teclado sem fio com touchpad integrado, ideal para smart TV e home office.',
    descEn: 'Wireless keyboard with built-in touchpad — perfect for smart TVs and home office.',
    variants: [{ sku: 'ELE-LGK400', label: 'Único', priceUsd: 39.0, stock: 25 }],
  },
  {
    slug: 'ue-wonderboom-2',
    category: 'electronica',
    brand: 'Ultimate Ears',
    name: 'Parlante Portátil Wonderboom 2',
    icon: 'speaker',
    featured: false,
    descEs: 'Parlante portátil resistente al agua con sonido 360° y 13 horas de batería.',
    descPt: 'Caixa de som portátil à prova d’água com som 360° e 13 horas de bateria.',
    descEn: 'Waterproof portable speaker with 360° sound and 13 hours of battery life.',
    variants: [{ sku: 'ELE-UEWB2', label: 'Único', priceUsd: 69.0, stock: 20 }],
  },
  {
    slug: 'xiaomi-power-bank-2s',
    category: 'electronica',
    brand: 'Xiaomi',
    name: 'Power Bank 2S 10000 mAh',
    icon: 'powerbank',
    featured: false,
    descEs: 'Batería portátil de 10.000 mAh con doble salida USB y carga rápida.',
    descPt: 'Bateria portátil de 10.000 mAh com dupla saída USB e carga rápida.',
    descEn: '10,000 mAh portable battery with dual USB output and fast charging.',
    variants: [{ sku: 'ELE-XPB-2S', label: 'Único', priceUsd: 25.0, stock: 35 }],
  },
  {
    slug: 'jbl-flip-6',
    category: 'electronica',
    brand: 'JBL',
    name: 'Parlante JBL Flip 6',
    icon: 'speaker',
    featured: true,
    descEs: 'Sonido JBL Original Pro con graves profundos, IP67 y 12 horas de reproducción.',
    descPt: 'Som JBL Original Pro com graves profundos, IP67 e 12 horas de reprodução.',
    descEn: 'JBL Original Pro sound with deep bass, IP67 rating and 12 hours of playtime.',
    variants: [{ sku: 'ELE-JBLF6', label: 'Único', priceUsd: 119.0, stock: 16 }],
  },
  {
    slug: 'sony-wh-ch520',
    category: 'electronica',
    brand: 'Sony',
    name: 'Auriculares WH-CH520',
    icon: 'headphones',
    featured: false,
    descEs: 'Auriculares inalámbricos on-ear con 50 horas de batería y conexión multipunto.',
    descPt: 'Fones sem fio on-ear com 50 horas de bateria e conexão multiponto.',
    descEn: 'Wireless on-ear headphones with 50-hour battery and multipoint connection.',
    variants: [{ sku: 'ELE-SNYCH520', label: 'Único', priceUsd: 59.0, stock: 22 }],
  },
  {
    slug: 'nintendo-switch-lite',
    category: 'electronica',
    brand: 'Nintendo',
    name: 'Consola Switch Lite',
    icon: 'console',
    featured: false,
    descEs: 'Consola portátil compacta y liviana, dedicada al juego en modo portátil.',
    descPt: 'Console portátil compacto e leve, dedicado ao jogo em modo portátil.',
    descEn: 'Compact, lightweight handheld console dedicated to portable play.',
    variants: [{ sku: 'ELE-NSWL', label: 'Único', priceUsd: 219.0, stock: 10 }],
  },
  // ----------------------- COMESTIBLES -----------------------
  {
    slug: 'toblerone-leche-360',
    category: 'comestibles',
    brand: 'Toblerone',
    name: 'Chocolate con Leche 360 g',
    icon: 'chocolate',
    featured: true,
    descEs: 'El triángulo suizo clásico con miel y turrón de almendras. Formato viajero de 360 g.',
    descPt: 'O triângulo suíço clássico com mel e torrone de amêndoas. Formato viagem de 360 g.',
    descEn: 'The classic Swiss triangle with honey and almond nougat. 360 g travel format.',
    variants: [{ sku: 'COM-TOB-360', label: '360 g', priceUsd: 12.0, stock: 60 }],
  },
  {
    slug: 'lindt-lindor-surtido-200',
    category: 'comestibles',
    brand: 'Lindt',
    name: 'Lindor Surtido 200 g',
    icon: 'candybox',
    featured: false,
    descEs: 'Bombones Lindor de centro cremoso en surtido de leche, blanco y amargo.',
    descPt: 'Bombons Lindor de centro cremoso em sortido ao leite, branco e amargo.',
    descEn: 'Lindor truffles with a smooth melting centre — milk, white and dark assortment.',
    variants: [{ sku: 'COM-LIN-200', label: '200 g', priceUsd: 11.0, stock: 45 }],
  },
  {
    slug: 'ferrero-rocher-t24',
    category: 'comestibles',
    brand: 'Ferrero',
    name: 'Ferrero Rocher x24',
    icon: 'candybox',
    featured: false,
    descEs: 'Avellana entera, crema de avellanas y oblea crocante bañada en chocolate. Caja x24.',
    descPt: 'Avelã inteira, creme de avelãs e wafer crocante banhado em chocolate. Caixa x24.',
    descEn: 'Whole hazelnut, hazelnut cream and crisp wafer coated in chocolate. Box of 24.',
    variants: [{ sku: 'COM-FER-T24', label: 'Caja x24', priceUsd: 15.0, stock: 38 }],
  },
  {
    slug: 'mms-peanut-400',
    category: 'comestibles',
    brand: "M&M's",
    name: "M&M's Peanut 400 g",
    icon: 'candybox',
    featured: false,
    descEs: 'Maní recubierto de chocolate con leche y confite de colores, en bolsa familiar.',
    descPt: 'Amendoim coberto de chocolate ao leite e confeito colorido, em embalagem família.',
    descEn: 'Peanuts covered in milk chocolate and colourful candy shell — family size bag.',
    variants: [{ sku: 'COM-MMS-400', label: '400 g', priceUsd: 9.0, stock: 50 }],
  },
  {
    slug: 'havanna-alfajores-12',
    category: 'comestibles',
    brand: 'Havanna',
    name: 'Alfajores Mixtos x12',
    icon: 'candybox',
    featured: false,
    descEs: 'El alfajor argentino por excelencia: dulce de leche y chocolate o merengue italiano.',
    descPt: 'O alfajor argentino por excelência: doce de leite e chocolate ou merengue italiano.',
    descEn: 'Argentina’s signature alfajor: dulce de leche with chocolate or Italian meringue.',
    variants: [{ sku: 'COM-HAV-12', label: 'Caja x12', priceUsd: 18.0, stock: 30 }],
  },
  {
    slug: 'twinings-english-breakfast',
    category: 'comestibles',
    brand: 'Twinings',
    name: 'English Breakfast x100',
    icon: 'tea',
    featured: false,
    descEs: 'Blend clásico de té negro, robusto y equilibrado. Caja de 100 saquitos.',
    descPt: 'Blend clássico de chá preto, robusto e equilibrado. Caixa com 100 sachês.',
    descEn: 'Classic robust and balanced black tea blend. Box of 100 tea bags.',
    variants: [{ sku: 'COM-TWI-100', label: 'Caja x100', priceUsd: 10.0, stock: 26 }],
  },
  // -------------------------- MODA ---------------------------
  {
    slug: 'rayban-aviator-classic',
    category: 'moda',
    brand: 'Ray-Ban',
    name: 'Aviator Classic',
    icon: 'sunglasses',
    featured: true,
    descEs: 'El icónico aviador con lentes de cristal G-15 y protección UV total.',
    descPt: 'O icônico aviador com lentes de cristal G-15 e proteção UV total.',
    descEn: 'The iconic aviator with G-15 crystal lenses and full UV protection.',
    variants: [{ sku: 'MOD-RBA-G15', label: 'Único', priceUsd: 129.0, stock: 14 }],
  },
  {
    slug: 'casio-gshock-ga2100',
    category: 'moda',
    brand: 'Casio',
    name: 'G-Shock GA-2100',
    icon: 'watch',
    featured: false,
    descEs: 'Resistencia G-Shock en perfil ultra delgado, con carcasa octogonal de carbono.',
    descPt: 'Resistência G-Shock em perfil ultrafino, com caixa octogonal de carbono.',
    descEn: 'G-Shock toughness in an ultra-slim profile with octagonal carbon case.',
    variants: [{ sku: 'MOD-GSH-2100', label: 'Único', priceUsd: 99.0, stock: 12 }],
  },
  {
    slug: 'swatch-big-bold',
    category: 'moda',
    brand: 'Swatch',
    name: 'Big Bold',
    icon: 'watch',
    featured: false,
    descEs: 'Reloj suizo de 47 mm con espíritu urbano y correa de silicona.',
    descPt: 'Relógio suíço de 47 mm com espírito urbano e pulseira de silicone.',
    descEn: 'A 47 mm Swiss watch with urban attitude and silicone strap.',
    variants: [{ sku: 'MOD-SWA-BB', label: 'Único', priceUsd: 85.0, stock: 15 }],
  },
  {
    slug: 'tommy-billetera-cuero',
    category: 'moda',
    brand: 'Tommy Hilfiger',
    name: 'Billetera de Cuero',
    icon: 'wallet',
    featured: false,
    descEs: 'Billetera plegable de cuero genuino con múltiples tarjeteros y monedero.',
    descPt: 'Carteira dobrável de couro genuíno com vários porta-cartões e porta-moedas.',
    descEn: 'Genuine leather bifold wallet with multiple card slots and coin pocket.',
    variants: [{ sku: 'MOD-TH-WAL', label: 'Único', priceUsd: 49.0, stock: 20 }],
  },
  {
    slug: 'pashmina-austral',
    category: 'moda',
    brand: 'Atlántico Sur Selection',
    name: 'Pashmina Seda y Lana',
    icon: 'scarf',
    featured: false,
    descEs: 'Pashmina suave de seda y lana, perfecta para el clima fueguino. Varios colores.',
    descPt: 'Pashmina macia de seda e lã, perfeita para o clima fueguino. Várias cores.',
    descEn: 'Soft silk-and-wool pashmina, perfect for the Fuegian climate. Assorted colours.',
    variants: [{ sku: 'MOD-PSH-AUS', label: 'Único', priceUsd: 35.0, stock: 24 }],
  },
  // ------------------------ JUGUETES -------------------------
  {
    slug: 'lego-classic-creativa',
    category: 'juguetes',
    brand: 'LEGO',
    name: 'Classic Caja Creativa 484 pzs',
    icon: 'brick',
    featured: true,
    descEs: 'Ladrillos LEGO de 33 colores con ruedas, ojos y piezas especiales para crear sin límites.',
    descPt: 'Peças LEGO em 33 cores com rodas, olhos e peças especiais para criar sem limites.',
    descEn: 'LEGO bricks in 33 colours with wheels, eyes and special pieces for limitless building.',
    variants: [{ sku: 'JUG-LEG-484', label: '484 piezas', priceUsd: 45.0, stock: 18 }],
  },
  {
    slug: 'hot-wheels-pack5',
    category: 'juguetes',
    brand: 'Hot Wheels',
    name: 'Pack x5 Vehículos',
    icon: 'toycar',
    featured: false,
    descEs: 'Cinco vehículos Hot Wheels a escala 1:64 con diseños temáticos surtidos.',
    descPt: 'Cinco veículos Hot Wheels em escala 1:64 com designs temáticos sortidos.',
    descEn: 'Five 1:64-scale Hot Wheels vehicles in assorted themed designs.',
    variants: [{ sku: 'JUG-HW-P5', label: 'Pack x5', priceUsd: 12.0, stock: 34 }],
  },
  {
    slug: 'uno-cartas',
    category: 'juguetes',
    brand: 'Mattel Games',
    name: 'UNO Clásico',
    icon: 'cards',
    featured: false,
    descEs: 'El juego de cartas más famoso del mundo, para toda la familia. De 2 a 10 jugadores.',
    descPt: 'O jogo de cartas mais famoso do mundo, para toda a família. De 2 a 10 jogadores.',
    descEn: 'The world’s most famous card game, fun for the whole family. 2 to 10 players.',
    variants: [{ sku: 'JUG-UNO', label: 'Único', priceUsd: 8.0, stock: 40 }],
  },
  {
    slug: 'peluche-pinguino-austral',
    category: 'juguetes',
    brand: 'Wild Republic',
    name: 'Peluche Pingüino Austral 30 cm',
    icon: 'teddy',
    featured: false,
    descEs: 'Un recuerdo del fin del mundo: pingüino de peluche súper suave de 30 cm.',
    descPt: 'Uma lembrança do fim do mundo: pinguim de pelúcia super macio de 30 cm.',
    descEn: 'A keepsake from the end of the world: super-soft 30 cm penguin plush.',
    variants: [{ sku: 'JUG-PIN-30', label: '30 cm', priceUsd: 19.0, stock: 28 }],
  },
  {
    slug: 'cubo-rubik-3x3',
    category: 'juguetes',
    brand: "Rubik's",
    name: 'Cubo Rubik 3x3',
    icon: 'cube',
    featured: false,
    descEs: 'El rompecabezas clásico de 43 trillones de combinaciones y una sola solución.',
    descPt: 'O quebra-cabeça clássico de 43 trilhões de combinações e uma única solução.',
    descEn: 'The classic puzzle: 43 quintillion combinations, only one solution.',
    variants: [{ sku: 'JUG-RUB-3X3', label: 'Único', priceUsd: 14.0, stock: 32 }],
  },
  // -------------------------- VIAJE --------------------------
  {
    slug: 'samsonite-cabina-55',
    category: 'viaje',
    brand: 'Samsonite',
    name: 'Valija Cabina 55 cm',
    icon: 'suitcase',
    featured: true,
    descEs: 'Valija rígida de cabina con 4 ruedas dobles, candado TSA y garantía internacional.',
    descPt: 'Mala rígida de cabine com 4 rodas duplas, cadeado TSA e garantia internacional.',
    descEn: 'Hard-shell cabin case with 4 double wheels, TSA lock and international warranty.',
    variants: [{ sku: 'VIA-SAM-55', label: '55 cm', priceUsd: 189.0, stock: 10 }],
  },
  {
    slug: 'swissgear-mochila-28',
    category: 'viaje',
    brand: 'SwissGear',
    name: 'Mochila Urbana 28 L',
    icon: 'backpack',
    featured: false,
    descEs: 'Mochila de 28 litros con compartimento acolchado para notebook de 15,6".',
    descPt: 'Mochila de 28 litros com compartimento acolchoado para notebook de 15,6".',
    descEn: '28-litre backpack with padded compartment for a 15.6" laptop.',
    variants: [{ sku: 'VIA-SWG-28', label: '28 L', priceUsd: 79.0, stock: 16 }],
  },
  {
    slug: 'samsonite-neceser',
    category: 'viaje',
    brand: 'Samsonite',
    name: 'Neceser de Viaje',
    icon: 'pouch',
    featured: false,
    descEs: 'Neceser compacto con gancho colgante y bolsillos internos impermeables.',
    descPt: 'Nécessaire compacta com gancho suspenso e bolsos internos impermeáveis.',
    descEn: 'Compact toiletry kit with hanging hook and waterproof inner pockets.',
    variants: [{ sku: 'VIA-SAM-NEC', label: 'Único', priceUsd: 32.0, stock: 22 }],
  },
  {
    slug: 'cabeau-almohada-viaje',
    category: 'viaje',
    brand: 'Cabeau',
    name: 'Almohada de Viaje Evolution',
    icon: 'pillow',
    featured: false,
    descEs: 'Almohada cervical viscoelástica con soporte 360° y funda lavable.',
    descPt: 'Travesseiro cervical viscoelástico com suporte 360° e capa lavável.',
    descEn: 'Memory-foam neck pillow with 360° support and washable cover.',
    variants: [{ sku: 'VIA-CAB-EVO', label: 'Único', priceUsd: 39.0, stock: 20 }],
  },
  // -------------------------- HOME ---------------------------
  {
    slug: 'stanley-termo-clasico',
    category: 'home',
    brand: 'Stanley',
    name: 'Termo Clásico 1 L',
    icon: 'thermo',
    featured: true,
    descEs: 'El termo legendario: acero inoxidable, 24 horas de temperatura y garantía de por vida.',
    descPt: 'A garrafa térmica lendária: aço inox, 24 horas de temperatura e garantia vitalícia.',
    descEn: 'The legendary flask: stainless steel, 24-hour temperature retention, lifetime warranty.',
    variants: [{ sku: 'HOM-STA-1L', label: '1 L', priceUsd: 55.0, stock: 24 }],
  },
  {
    slug: 'set-matero-austral',
    category: 'home',
    brand: 'Atlántico Sur Selection',
    name: 'Set Matero Calabaza + Bombilla',
    icon: 'mate',
    featured: false,
    descEs: 'Mate de calabaza curado con virola de alpaca y bombilla pico de loro.',
    descPt: 'Cuia de porongo curada com detalhe de alpaca e bomba pico de loro.',
    descEn: 'Cured gourd mate with alpaca trim and traditional bombilla straw.',
    variants: [{ sku: 'HOM-MAT-SET', label: 'Set', priceUsd: 28.0, stock: 26 }],
  },
  {
    slug: 'victorinox-swiss-classic',
    category: 'home',
    brand: 'Victorinox',
    name: 'Set Cuchillos Swiss Classic',
    icon: 'knife',
    featured: false,
    descEs: 'Set de cuchillos de cocina suizos con hojas de acero inoxidable de alta precisión.',
    descPt: 'Conjunto de facas de cozinha suíças com lâminas de aço inox de alta precisão.',
    descEn: 'Swiss kitchen knife set with high-precision stainless steel blades.',
    variants: [{ sku: 'HOM-VIC-SET', label: 'Set x3', priceUsd: 42.0, stock: 18 }],
  },
  {
    slug: 'bialetti-moka-express',
    category: 'home',
    brand: 'Bialetti',
    name: 'Moka Express 3 Tazas',
    icon: 'moka',
    featured: false,
    descEs: 'La cafetera italiana original de aluminio, ícono del espresso casero desde 1933.',
    descPt: 'A cafeteira italiana original de alumínio, ícone do espresso caseiro desde 1933.',
    descEn: 'The original Italian aluminium coffee maker, a home-espresso icon since 1933.',
    variants: [{ sku: 'HOM-BIA-3T', label: '3 tazas', priceUsd: 36.0, stock: 21 }],
  },
];
